'use client';
import { useState } from 'react';
import { getPropertyIcon, PROPERTY_TYPES, AREA_UNITS, WEIGHT_UNITS } from '@/lib/propertyTypes';

/**
 * Compute summary units (kanal+marla, tola, etc.) for a given fraction of properties.
 * Returns an array of formatted unit strings like ["2.19 Kanal", "10.94 Tola"].
 */
function computeUnitTotals(properties, fraction) {
  if (!properties || !fraction || fraction <= 0) return [];

  const areaTotals = {}; // unit -> total
  const weightTotals = {};
  const quantityTotals = {};

  for (const p of properties) {
    if (p.areaValue && p.areaUnit) {
      areaTotals[p.areaUnit] = (areaTotals[p.areaUnit] || 0) + p.areaValue * fraction;
    }
    if (p.weightValue && p.weightUnit) {
      weightTotals[p.weightUnit] = (weightTotals[p.weightUnit] || 0) + p.weightValue * fraction;
    }
    if (p.quantity) {
      const key = p.type || 'units';
      quantityTotals[key] = (quantityTotals[key] || 0) + p.quantity * fraction;
    }
  }

  const out = [];
  for (const [unit, total] of Object.entries(areaTotals)) {
    out.push(`${total.toFixed(3)} ${AREA_UNITS[unit]?.label || unit}`);
  }
  for (const [unit, total] of Object.entries(weightTotals)) {
    out.push(`${total.toFixed(3)} ${WEIGHT_UNITS[unit]?.label || unit}`);
  }
  for (const [type, total] of Object.entries(quantityTotals)) {
    const label = PROPERTY_TYPES[type]?.label || type;
    out.push(`${total.toFixed(2)} ${label.toLowerCase()}`);
  }
  return out;
}

export default function InheritanceResults({ result, deceasedName }) {
  const [downloading, setDownloading] = useState(false);
  const [activeView, setActiveView] = useState('multigen');
  const [showUnits, setShowUnits] = useState(true); // Toggle: show kanal/tola or just rupees

  const fmt = (n) => Number(n).toLocaleString('en-PK', { maximumFractionDigits: 0 });

  if (result.error) {
    return (
      <div className="card p-8 border-terracotta">
        <div className="text-terracotta font-medium">{result.error}</div>
      </div>
    );
  }

  const livingHeirs = result.shares.filter(s => !s.noHeirs);
  const equalShare = livingHeirs.length > 0 ? result.netEstate / livingHeirs.length : 0;

  // The full property list of the deceased (for unit computation in hierarchy)
  // Note: we use the FULL properties from the original deceased, scaled by each branch's fraction
  const allProperties = result.properties || [];
  // Reconstruct properties with their unit data (the API stripped some — need to access from propertyDistribution)
  const fullProperties = (result.propertyDistribution || []).map(pd => pd.property).map(p => ({
    type: p.type,
    value: p.value,
    areaValue: p.totalArea?.value || null,
    areaUnit: p.totalArea?.unit || null,
    weightValue: p.totalWeight?.value || null,
    weightUnit: p.totalWeight?.unit || null,
    quantity: p.totalQuantity || null,
  }));

  async function downloadPDF() {
    setDownloading(true);
    try {
      const { default: jsPDF } = await import('jspdf');
      const autoTableMod = await import('jspdf-autotable');
      const autoTable = autoTableMod.default || autoTableMod;
      const doc = new jsPDF();

      doc.setFontSize(11); doc.setFont('helvetica', 'italic');
      doc.text('بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ', 105, 16, { align: 'center' });
      doc.setFontSize(20); doc.setFont('helvetica', 'bold');
      doc.text('Certificate of Islamic Inheritance', 105, 26, { align: 'center' });
      doc.setFontSize(10); doc.setFont('helvetica', 'normal');
      doc.text('Hanafi Faraid · Generated by Mirath', 105, 32, { align: 'center' });
      doc.setDrawColor(168, 136, 75); doc.setLineWidth(0.5);
      doc.line(20, 36, 190, 36);

      doc.setFontSize(11);
      doc.text('Deceased:', 14, 46);
      doc.setFont('helvetica', 'bold');
      doc.text(deceasedName, 45, 46);
      doc.setFont('helvetica', 'normal');
      doc.text('Date of distribution:', 14, 53);
      doc.text(new Date().toLocaleDateString('en-PK', { year: 'numeric', month: 'long', day: 'numeric' }), 60, 53);

      autoTable(doc, {
        startY: 65,
        head: [['Item', 'Amount (PKR)']],
        body: [
          ['Total Estate (Gross)', fmt(result.totalEstate)],
          ['(–) Funeral Costs', fmt(result.funeralCost)],
          ['(–) Debts', fmt(result.debts)],
          ['(–) Bequest', fmt(result.bequest)],
          ['Net Distributable', fmt(result.netEstate)],
        ],
        theme: 'grid',
        headStyles: { fillColor: [26, 22, 20], textColor: [250, 246, 238] },
        styles: { fontSize: 10 },
      });

      let yPos = doc.lastAutoTable.finalY + 10;
      doc.setFontSize(12); doc.setFont('helvetica', 'bold');
      doc.text('Heir Distribution', 14, yPos);

      autoTable(doc, {
        startY: yPos + 3,
        head: [['Heir', 'Relationship', 'Units', '%', 'Amount (PKR)']],
        body: result.shares.map(s => {
          const units = computeUnitTotals(fullProperties, s.fractionDecimal).join(' · ') || '—';
          return [
            s.name + (s.cascadedFrom ? `\n(via ${s.cascadedFrom})` : ''),
            s.relationship,
            units,
            `${parseFloat(s.percentage).toFixed(2)}%`,
            fmt(s.amount),
          ];
        }),
        theme: 'striped',
        headStyles: { fillColor: [184, 92, 58], textColor: [255, 255, 255] },
        styles: { fontSize: 8 },
      });

      yPos = doc.lastAutoTable.finalY + 8;
      doc.setFont('helvetica', 'italic'); doc.setFontSize(9);
      doc.text(
        '"Allah commands you regarding your children: for the male, a share equivalent to that of two females..."',
        105, Math.min(yPos + 200, 280), { align: 'center', maxWidth: 170 }
      );

      doc.save(`certificate-${deceasedName.replace(/\s+/g, '-')}.pdf`);
    } catch (err) {
      alert('PDF generation failed: ' + err.message);
    } finally {
      setDownloading(false);
    }
  }

  function shareWhatsAppEnglish() {
    let msg = `*Inheritance Distribution — ${deceasedName}*\n\n`;
    msg += `Total Estate: ₨${fmt(result.totalEstate)}\n`;
    msg += `Net Distributable: ₨${fmt(result.netEstate)}\n\n`;
    msg += `*Heir Shares (Hanafi Faraid):*\n`;
    for (const s of result.shares) {
      const units = computeUnitTotals(fullProperties, s.fractionDecimal).join(' · ');
      msg += `\n• *${s.name}* (${s.relationship})\n  ${parseFloat(s.percentage).toFixed(2)}% = ₨${fmt(s.amount)}`;
      if (units) msg += `\n  Property: ${units}`;
      if (s.cascadedFrom) msg += `\n  _via ${s.cascadedFrom}_`;
    }
    msg += `\n\n_Calculated using Mirath app — Hanafi Faraid rules._`;
    window.open(`https://wa.me/?text=${encodeURIComponent(msg)}`, '_blank');
  }

  function shareWhatsAppUrdu() {
    let msg = `*وراثت کی تقسیم — ${deceasedName}*\n\n`;
    msg += `کل ترکہ: ₨${fmt(result.totalEstate)}\n\n`;
    msg += `*وارثوں کے حصے:*\n`;
    const relMap = {
      'Husband': 'شوہر', 'Wife': 'بیوی', 'Father': 'والد', 'Mother': 'والدہ',
      'Son': 'بیٹا', 'Daughter': 'بیٹی', 'Grandmother': 'دادی/نانی',
    };
    for (const s of result.shares) {
      const urduRel = relMap[s.relationship] || s.relationship;
      const units = computeUnitTotals(fullProperties, s.fractionDecimal).join(' · ');
      msg += `\n• *${s.name}* (${urduRel})\n  ₨${fmt(s.amount)}`;
      if (units) msg += `\n  جائیداد: ${units}`;
    }
    msg += `\n\n_میراث ایپ سے حساب شدہ_`;
    window.open(`https://wa.me/?text=${encodeURIComponent(msg)}`, '_blank');
  }

  return (
    <div className="space-y-6 animate-fade-up">
      {/* Header */}
      <div className="card p-8">
        <div className="flex items-start justify-between flex-wrap gap-4 mb-6">
          <div>
            <div className="text-xs tracking-[0.3em] uppercase text-terracotta mb-2">
              {result.isSimulation ? '⚠ Wasiyyah Simulation' : 'Inheritance Distribution'}
              {result.hasCascades && ' · with Representation'}
            </div>
            <h2 className="display-font text-4xl">Estate of {deceasedName}</h2>
            {result.isSimulation && (
              <div className="mt-2 text-sm text-terracotta italic">Hypothetical — this person is currently alive</div>
            )}
          </div>
        </div>

        <div className="grid sm:grid-cols-2 md:grid-cols-4 gap-4 mb-6 border-t border-black/10 pt-6">
          <div>
            <div className="text-xs opacity-60 uppercase tracking-wider mb-1">Total Estate</div>
            <div className="mono-font text-xl">₨ {fmt(result.totalEstate)}</div>
          </div>
          <div>
            <div className="text-xs opacity-60 uppercase tracking-wider mb-1">Deductions</div>
            <div className="mono-font text-xl text-terracotta">– ₨ {fmt(result.funeralCost + result.debts + result.bequest)}</div>
          </div>
          <div>
            <div className="text-xs opacity-60 uppercase tracking-wider mb-1">Net Estate</div>
            <div className="mono-font text-xl font-semibold">₨ {fmt(result.netEstate)}</div>
          </div>
          <div>
            <div className="text-xs opacity-60 uppercase tracking-wider mb-1">Heirs</div>
            <div className="mono-font text-xl">{result.shares?.length || 0}</div>
          </div>
        </div>

        {/* Property summary in header */}
        {fullProperties.length > 0 && (
          <div className="border-t border-black/10 pt-4 mb-4">
            <div className="text-xs opacity-60 uppercase tracking-wider mb-2 font-semibold">📦 Total Property Holdings</div>
            <div className="flex flex-wrap gap-3 text-sm">
              {computeUnitTotals(fullProperties, 1).map((u, i) => (
                <div key={i} className="px-3 py-1.5 bg-cream border border-black/10 mono-font">
                  {u}
                </div>
              ))}
            </div>
          </div>
        )}

        <div className="flex flex-wrap gap-2 border-t border-black/10 pt-4">
          <button onClick={downloadPDF} disabled={downloading} className="btn-primary text-sm">
            {downloading ? 'Generating…' : '📄 Certificate PDF'}
          </button>
          <button onClick={shareWhatsAppEnglish} className="btn-secondary text-sm">💬 WhatsApp (English)</button>
          <button onClick={shareWhatsAppUrdu} className="btn-secondary text-sm">💬 WhatsApp (Urdu)</button>
        </div>

        <div className="space-y-2 mt-4">
          {result.awlApplied && (
            <div className="text-sm bg-sage/10 border-l-2 border-sage px-4 py-2">
              <span className="font-semibold">⚖ Awl applied:</span> Shares exceeded 1, all reduced proportionally
            </div>
          )}
          {result.raddApplied && (
            <div className="text-sm bg-gold/10 border-l-2 border-gold px-4 py-2">
              <span className="font-semibold">⤴ Radd applied:</span> No male agnates; remainder returned to eligible heirs
            </div>
          )}
          {result.hasCascades && (
            <div className="text-sm bg-terracotta/10 border-l-2 border-terracotta px-4 py-2">
              <span className="font-semibold">🔁 Representation:</span> Predeceased heirs' shares cascaded to descendants
            </div>
          )}
        </div>

        {result.wasiyyahValidation && result.wasiyyahValidation.requestedBequest > 0 && (
          <div className={`mt-4 p-4 border-l-4 ${result.wasiyyahValidation.isValid ? 'bg-sage/10 border-sage' : 'bg-terracotta/10 border-terracotta'}`}>
            <div className="font-semibold mb-1">
              {result.wasiyyahValidation.isValid ? '✓' : '✗'} Wasiyyah Validation
            </div>
            <div className="text-sm">
              Requested: ₨{fmt(result.wasiyyahValidation.requestedBequest)} ({result.wasiyyahValidation.percentOfEstate.toFixed(1)}%)
              <br/>Maximum (1/3): ₨{fmt(result.wasiyyahValidation.maxAllowed)}
            </div>
          </div>
        )}
      </div>

      {/* View selector */}
      <div className="card p-2 flex flex-wrap gap-1 items-center">
        {[
          { id: 'multigen', label: '🌳 Full Hierarchy' },
          { id: 'summary', label: '📋 Summary' },
          { id: 'property', label: '🏠 Per Property' },
          { id: 'scholar', label: '🕌 Scholar View' },
          { id: 'dispute', label: '⚖ Dispute Resolver' },
          { id: 'compare', label: '📊 vs Equal' },
          ...(result.hasCascades ? [{ id: 'cascade', label: '🔁 Cascade Flow' }] : []),
        ].map(v => (
          <button
            key={v.id}
            onClick={() => setActiveView(v.id)}
            className={`px-4 py-2 text-sm transition-colors ${
              activeView === v.id ? 'bg-ink text-cream' : 'hover:bg-cream'
            }`}
          >
            {v.label}
          </button>
        ))}

        {/* Property unit toggle - hide for views where it doesn't apply */}
        {fullProperties.length > 0 && ['multigen', 'summary'].includes(activeView) && (
          <label className="ml-auto flex items-center gap-2 px-3 py-2 text-sm cursor-pointer border border-black/15 hover:bg-cream">
            <input
              type="checkbox"
              checked={showUnits}
              onChange={e => setShowUnits(e.target.checked)}
              className="cursor-pointer"
            />
            <span>Show property units (kanal/tola)</span>
          </label>
        )}
      </div>

      {/* ⭐ MULTI-GENERATION WITH NATIVE UNITS */}
      {activeView === 'multigen' && result.multiGeneration && (
        <div className="space-y-6">
          {/* Root level: original deceased */}
          <div className="card p-6 bg-gradient-to-br from-cream to-parchment">
            <div className="text-xs tracking-[0.3em] uppercase text-terracotta mb-2 font-semibold">
              🌳 Generation 1 (Root)
            </div>
            <h3 className="display-font text-2xl mb-1">{result.multiGeneration.root.name}'s Estate</h3>
            <div className="text-sm opacity-70 mb-1">
              Net Distributable: ₨ {fmt(result.multiGeneration.root.netEstate)} · {result.multiGeneration.branches.length} direct heirs
            </div>
            {showUnits && fullProperties.length > 0 && (
              <div className="flex flex-wrap gap-2 mb-4 text-xs">
                {computeUnitTotals(fullProperties, 1).map((u, i) => (
                  <span key={i} className="px-2 py-0.5 bg-ink text-cream mono-font">{u}</span>
                ))}
              </div>
            )}

            <div className="overflow-x-auto mt-4">
              <table className="w-full text-sm">
                <thead className="border-b-2 border-ink">
                  <tr>
                    <th className="text-left py-2 font-semibold">Heir</th>
                    <th className="text-left py-2 font-semibold">Relationship</th>
                    {showUnits && <th className="text-left py-2 font-semibold">Property Share</th>}
                    <th className="text-right py-2 font-semibold">%</th>
                    <th className="text-right py-2 font-semibold">Amount (₨)</th>
                  </tr>
                </thead>
                <tbody>
                  {result.multiGeneration.branches.map((b, i) => {
                    const units = computeUnitTotals(fullProperties, b.fractionDecimal);
                    return (
                      <tr key={i} className="border-b border-black/5 hover:bg-cream/50">
                        <td className="py-2 font-medium">
                          {b.heirName}
                          {!b.isAlive && <span className="ml-2 text-xs text-terracotta">✝</span>}
                        </td>
                        <td className="py-2 opacity-70 text-xs uppercase tracking-wider">{b.relationship}</td>
                        {showUnits && (
                          <td className="py-2">
                            {units.length > 0 ? (
                              <div className="flex flex-col gap-0.5">
                                {units.map((u, j) => (
                                  <span key={j} className="mono-font text-xs">
                                    {u.includes('Kanal') || u.includes('Marla') || u.includes('Acre') ? '🌾' :
                                     u.includes('Tola') || u.includes('Gram') ? '✦' : '◇'}{' '}
                                    <span className="text-sage font-semibold">{u}</span>
                                  </span>
                                ))}
                              </div>
                            ) : <span className="opacity-40 text-xs">—</span>}
                          </td>
                        )}
                        <td className="py-2 text-right mono-font">{parseFloat(b.percentage).toFixed(2)}%</td>
                        <td className="py-2 text-right mono-font font-semibold">{fmt(b.amount)}</td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>

          {/* Divider */}
          {result.multiGeneration.branches.filter(b => b.subDistribution).length > 0 && (
            <div className="border-t-2 border-dashed border-gold/30 pt-6">
              <div className="text-center mb-6">
                <div className="text-xs tracking-[0.3em] uppercase text-gold font-semibold mb-2">
                  ↓ NEXT GENERATIONS ↓
                </div>
                <div className="display-font italic text-xl opacity-70">
                  How each heir's share would further distribute
                </div>
              </div>
            </div>
          )}

          {/* Each branch table */}
          {result.multiGeneration.branches.filter(b => b.subDistribution).map((branch, idx) => (
            <BranchTable
              key={idx}
              branch={branch}
              generation={2}
              fmt={fmt}
              fullProperties={fullProperties}
              parentFraction={branch.fractionDecimal}
              showUnits={showUnits}
            />
          ))}

          {result.multiGeneration.branches.filter(b => b.subDistribution).length === 0 && (
            <div className="card p-8 text-center opacity-70">
              <p className="text-sm">
                None of the direct heirs have their own descendants registered yet.
                <br/>Add more family members in the People tab to see the full multi-generation distribution.
              </p>
            </div>
          )}
        </div>
      )}

      {/* SUMMARY */}
      {activeView === 'summary' && (
        <div className="card p-8">
          <h3 className="display-font text-2xl mb-6">Final Distribution</h3>
          <div className="space-y-3">
            {result.shares.map((s, i) => {
              const units = computeUnitTotals(fullProperties, s.fractionDecimal);
              return (
                <div key={i} className="grid grid-cols-12 gap-3 items-baseline py-4 border-b border-black/5 last:border-0">
                  <div className={showUnits ? "col-span-12 md:col-span-4" : "col-span-12 md:col-span-6"}>
                    <div className="display-font text-xl">{s.name}</div>
                    <div className="text-xs tracking-wider uppercase text-terracotta">{s.relationship}</div>
                    {s.cascadedFrom && <div className="text-xs opacity-60 italic mt-1">via: {s.cascadedFrom}</div>}
                  </div>
                  {showUnits && (
                    <div className="col-span-6 md:col-span-3">
                      {units.length > 0 && (
                        <div className="space-y-1">
                          {units.map((u, j) => (
                            <div key={j} className="mono-font text-sm text-sage font-semibold">{u}</div>
                          ))}
                        </div>
                      )}
                    </div>
                  )}
                  <div className="col-span-6 md:col-span-2 text-center">
                    <div className="mono-font text-lg">{parseFloat(s.percentage).toFixed(2)}%</div>
                  </div>
                  <div className={showUnits ? "col-span-12 md:col-span-3 text-right" : "col-span-12 md:col-span-4 text-right"}>
                    <div className="mono-font text-2xl font-semibold">₨ {fmt(s.amount)}</div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* PER PROPERTY */}
      {activeView === 'property' && (
        <div className="space-y-4">
          <div className="card p-6 bg-sage/5">
            <div className="text-sm">
              <span className="font-semibold">🏠 Property-by-Property Distribution:</span> Each property split in its native unit.
            </div>
          </div>
          {(!result.propertyDistribution || result.propertyDistribution.length === 0) ? (
            <div className="card p-8 text-center opacity-70">No specific properties registered.</div>
          ) : (
            result.propertyDistribution.map((pb, idx) => (
              <div key={idx} className="card p-6">
                <div className="flex items-start justify-between mb-4 pb-4 border-b border-black/10">
                  <div className="flex items-center gap-3">
                    <span className="text-3xl">{getPropertyIcon(pb.property.type)}</span>
                    <div>
                      <div className="display-font text-2xl">{pb.property.name}</div>
                      <div className="text-xs opacity-60">
                        {PROPERTY_TYPES[pb.property.type]?.label}
                        {pb.property.subtype && ` · ${pb.property.subtype}`}
                        {pb.property.location && ` · ${pb.property.location}`}
                      </div>
                      <div className="text-sm mt-1 mono-font">
                        Total: {pb.property.totalArea && <span>{pb.property.totalArea.value} {pb.property.totalArea.unit} · </span>}
                        {pb.property.totalWeight && <span>{pb.property.totalWeight.value} {pb.property.totalWeight.unit} · </span>}
                        ₨ {fmt(pb.property.value)}
                      </div>
                    </div>
                  </div>
                </div>
                <div className="space-y-2">
                  {pb.allocations.map((a, i) => (
                    <div key={i} className="flex items-baseline justify-between gap-3 py-2 border-b border-black/5 last:border-0">
                      <div className="flex-1 min-w-0">
                        <div className="font-medium truncate">{a.heirName}</div>
                        <div className="text-xs opacity-60">{a.relationship} · {parseFloat(a.percentage).toFixed(2)}%</div>
                      </div>
                      <div className="text-right">
                        {a.areaValue && (
                          <div className="mono-font text-lg text-sage font-semibold">{a.areaValue.toFixed(3)} {a.areaUnitLabel}</div>
                        )}
                        {a.weightValue && (
                          <div className="mono-font text-lg text-gold font-semibold">{a.weightValue.toFixed(3)} {a.weightUnitLabel}</div>
                        )}
                        {a.quantity && !a.areaValue && !a.weightValue && (
                          <div className="mono-font text-lg">{a.quantity.toFixed(2)} units</div>
                        )}
                        <div className="mono-font text-sm opacity-70">≈ ₨ {fmt(a.monetaryAmount)}</div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ))
          )}
        </div>
      )}

      {/* SCHOLAR */}
      {activeView === 'scholar' && (
        <div className="card p-8">
          <h3 className="display-font text-2xl mb-2">🕌 Scholar Verification</h3>
          <p className="opacity-70 text-sm mb-6">Each share rooted in Quranic verses, Hadith, or scholarly consensus.</p>
          <div className="space-y-5">
            {result.shares.map((s, i) => (
              <div key={i} className="p-5 bg-cream border-l-2 border-gold">
                <div className="flex items-baseline justify-between mb-2 flex-wrap gap-2">
                  <div>
                    <span className="font-semibold">{s.name}</span>
                    <span className="text-xs ml-2 px-2 py-0.5 bg-ink text-cream">{s.relationship}</span>
                  </div>
                  <div className="mono-font font-semibold">{parseFloat(s.percentage).toFixed(2)}% · ₨ {fmt(s.amount)}</div>
                </div>
                {s.scholarVerification ? (
                  <>
                    <div className="text-xs tracking-wider uppercase text-terracotta font-semibold mt-3">📖 {s.scholarVerification.source}</div>
                    <div className="text-right text-xl my-2 leading-loose" lang="ar" style={{fontFamily: '"Noto Nastaliq Urdu", serif'}}>{s.scholarVerification.arabic}</div>
                    <div className="italic text-sm">"{s.scholarVerification.translation}"</div>
                    <div className="text-sm mt-2 opacity-80">{s.scholarVerification.explanation}</div>
                  </>
                ) : <div className="text-sm opacity-60 italic">Reason: {s.reason}</div>}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* DISPUTE */}
      {activeView === 'dispute' && (
        <div className="space-y-4">
          <div className="card p-6 bg-terracotta/5">
            <h3 className="display-font text-2xl mb-2">⚖ Dispute Resolver</h3>
            <p className="text-sm opacity-80">Share specific shares with their Quranic/Hadith basis via WhatsApp.</p>
          </div>
          {result.shares.map((s, i) => (
            <div key={i} className="card p-5">
              <div className="flex items-baseline justify-between mb-3 flex-wrap gap-2">
                <div className="font-semibold text-lg">{s.name} → ₨ {fmt(s.amount)}</div>
                {s.scholarVerification && (
                  <button
                    onClick={() => {
                      const msg = `*Inheritance Share Verification*\n\n${s.name} as ${s.relationship}: ${parseFloat(s.percentage).toFixed(2)}% = ₨${fmt(s.amount)}\n\n*Source:* ${s.scholarVerification.source}\n\n${s.scholarVerification.arabic}\n\n"${s.scholarVerification.translation}"\n\n${s.scholarVerification.explanation}`;
                      window.open(`https://wa.me/?text=${encodeURIComponent(msg)}`, '_blank');
                    }}
                    className="btn-secondary text-xs"
                  >💬 Share Source</button>
                )}
              </div>
              {s.scholarVerification && (
                <>
                  <div className="text-right text-lg leading-loose mb-2" lang="ar" style={{fontFamily: '"Noto Nastaliq Urdu", serif'}}>{s.scholarVerification.arabic}</div>
                  <div className="italic text-sm opacity-80">"{s.scholarVerification.translation}"</div>
                  <div className="text-xs mt-2 text-terracotta font-semibold">— {s.scholarVerification.source}</div>
                </>
              )}
            </div>
          ))}
        </div>
      )}

      {/* COMPARE */}
      {activeView === 'compare' && (
        <div className="card p-8 bg-sage/5 border-sage/30">
          <h3 className="display-font text-2xl mb-2">📊 Islamic vs Equal Distribution</h3>
          <p className="opacity-70 text-sm mb-5">Equal distribution is NOT permitted in Islam — for comparison only.</p>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-black/15">
                  <th className="text-left py-2">Heir</th>
                  <th className="text-right py-2">Islamic (₨)</th>
                  <th className="text-right py-2">Equal (₨)</th>
                  <th className="text-right py-2">Difference</th>
                </tr>
              </thead>
              <tbody>
                {result.shares.map((s, i) => {
                  const diff = s.amount - equalShare;
                  return (
                    <tr key={i} className="border-b border-black/5">
                      <td className="py-2">
                        <div className="font-medium">{s.name}</div>
                        <div className="text-xs opacity-60">{s.relationship}</div>
                      </td>
                      <td className="text-right mono-font">₨ {fmt(s.amount)}</td>
                      <td className="text-right mono-font opacity-70">₨ {fmt(equalShare)}</td>
                      <td className={`text-right mono-font ${diff > 0 ? 'text-sage' : 'text-terracotta'}`}>
                        {diff > 0 ? '+' : ''}{fmt(diff)}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* CASCADE */}
      {activeView === 'cascade' && result.cascadeChain && (
        <div className="card p-8">
          <h3 className="display-font text-2xl mb-2">🔁 Cascade Flow</h3>
          <div className="space-y-2 font-mono text-sm">
            {result.cascadeChain.map((c, i) => (
              <div key={i} style={{ paddingLeft: `${c.level * 24}px` }}
                   className={`flex items-center gap-3 py-1.5 ${c.cascaded ? 'text-terracotta' : ''}`}>
                <span className="opacity-60">{c.cascaded ? '↪' : '→'}</span>
                <span className="font-semibold">{c.to}</span>
                <span className="opacity-60 text-xs">({c.relationship})</span>
                <span className="ml-auto mono-font">₨ {fmt(c.amount)}</span>
                {c.isDeceased && <span className="text-xs text-terracotta">[deceased - cascading]</span>}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

/**
 * Branch table — shows ONE heir's branch with their sub-distribution.
 * Includes native units (kanal/tola) inline next to each sub-heir.
 */
function BranchTable({ branch, generation, fmt, fullProperties, parentFraction, showUnits = true }) {
  const genColors = ['', 'bg-sage/5', 'bg-gold/5', 'bg-terracotta/5', 'bg-cream'];
  const borderColors = ['', 'border-sage', 'border-gold', 'border-terracotta', 'border-ink'];

  if (!branch.subDistribution) return null;

  // Units owned by THIS branch (parent of these sub-heirs)
  const branchUnits = showUnits && fullProperties && fullProperties.length > 0
    ? computeUnitTotals(fullProperties, branch.fractionDecimal)
    : [];

  return (
    <div className="space-y-3">
      <div className={`card p-6 ${genColors[generation] || ''} border-l-4 ${borderColors[generation] || 'border-ink'}`}>
        <div className="flex items-baseline justify-between mb-4 flex-wrap gap-2">
          <div>
            <div className="text-xs tracking-[0.3em] uppercase text-terracotta font-semibold mb-1">
              🌳 Generation {generation} — {branch.heirName}'s Branch
            </div>
            <div className="display-font text-xl">
              {branch.heirName}
              <span className="text-sm opacity-60 ml-2">({branch.relationship})</span>
              {!branch.isAlive && <span className="text-xs text-terracotta ml-2">✝ deceased</span>}
            </div>
            <div className="text-sm opacity-70 mt-1">{branch.subDistribution.note}</div>
          </div>
          <div className="text-right">
            <div className="text-xs opacity-60 uppercase tracking-wider">Branch Total</div>
            <div className="mono-font text-2xl font-semibold">₨ {fmt(branch.amount)}</div>
            {branchUnits.length > 0 && (
              <div className="mt-1 space-y-0.5">
                {branchUnits.map((u, i) => (
                  <div key={i} className="mono-font text-xs text-sage font-semibold">{u}</div>
                ))}
              </div>
            )}
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="border-b-2 border-ink/30">
              <tr>
                <th className="text-left py-2 font-semibold">Heir</th>
                <th className="text-left py-2 font-semibold">Relationship</th>
                {showUnits && <th className="text-left py-2 font-semibold">Property Share</th>}
                <th className="text-right py-2 font-semibold">%</th>
                <th className="text-right py-2 font-semibold">Amount (₨)</th>
              </tr>
            </thead>
            <tbody>
              {branch.subDistribution.branches.map((sb, i) => {
                const trueFraction = (parentFraction || branch.fractionDecimal || 0) * (sb.fractionDecimal || 0);
                const units = showUnits ? computeUnitTotals(fullProperties, trueFraction) : [];
                return (
                  <tr key={i} className="border-b border-black/5">
                    <td className="py-2 font-medium">
                      {sb.heirName}
                      {!sb.isAlive && <span className="ml-2 text-xs text-terracotta">✝</span>}
                    </td>
                    <td className="py-2 opacity-70 text-xs uppercase tracking-wider">{sb.relationship}</td>
                    {showUnits && (
                      <td className="py-2">
                        {units.length > 0 ? (
                          <div className="flex flex-col gap-0.5">
                            {units.map((u, j) => (
                              <span key={j} className="mono-font text-xs">
                                {u.includes('Kanal') || u.includes('Marla') || u.includes('Acre') ? '🌾' :
                                 u.includes('Tola') || u.includes('Gram') ? '✦' : '◇'}{' '}
                                <span className="text-sage font-semibold">{u}</span>
                              </span>
                            ))}
                          </div>
                        ) : <span className="opacity-40 text-xs">—</span>}
                      </td>
                    )}
                    <td className="py-2 text-right mono-font">{parseFloat(sb.percentage).toFixed(2)}%</td>
                    <td className="py-2 text-right mono-font font-semibold">{fmt(sb.amount)}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>

      {/* Recursively render sub-branches */}
      {branch.subDistribution.branches.filter(sb => sb.subDistribution).length > 0 && (
        <div className="pl-6 border-l-2 border-dashed border-gold/30 space-y-3">
          {branch.subDistribution.branches.filter(sb => sb.subDistribution).map((sb, i) => {
            const childParentFraction = (parentFraction || branch.fractionDecimal || 0) * (sb.fractionDecimal || 0);
            return (
              <BranchTable
                key={i}
                branch={sb}
                generation={generation + 1}
                fmt={fmt}
                fullProperties={fullProperties}
                parentFraction={childParentFraction}
                showUnits={showUnits}
              />
            );
          })}
        </div>
      )}
    </div>
  );
}
